### ISSUE TITLE
Travis CI error

### ISSUE THREAD

**Issue by MakDon** [MakDon/calendar#1]
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/pyenv/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack 
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7
gyp ERR! stack   2.7.14
gyp ERR! stack 
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v10.15.3/bin/node" "/home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/MakDon/calendar/node_modules/nodejieba
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

and 

0.51s$ ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, scandir '/home/travis/build/MakDon/calendar/.nyc_output'
    at Object.readdirSync (fs.js:785:3)
    at NYC._loadReports (/home/travis/build/MakDon/calendar/node_modules/nyc/index.js:315:18)
    at NYC.report (/home/travis/build/MakDon/calendar/node_modules/nyc/index.js:302:8)
    at report (/home/travis/build/MakDon/calendar/node_modules/nyc/bin/nyc.js:205:7)
    at Object.<anonymous> (/home/travis/build/MakDon/calendar/node_modules/nyc/bin/nyc.js:131:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[error] "2019-05-14T12:01:33.622Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2019-05-14T12:01:33.625Z"  'input: ' ''
[error] "2019-05-14T12:01:33.625Z"  'error from convertLcovToCoveralls'
/home/travis/build/MakDon/calendar/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Failed to parse string

**Comment by MakDon** [comment]
Solved
